In [62]:
import matplotlib.pyplot as plt
import numpy as np
import os
from PIL import Image
import glob
from sklearn import metrics


In [63]:
def getCenterLabel(pixel):
    """
    outside = red = (255,0,0)
    inside = green = (255,255,0)
    lumen = yellow = (0,255,0)
    catheder shadow = blue = (0,0,255)
    artery wall = turquisw = (0,255,255)
    stent = pink = (255,0,255)
    
    input: RGB value of pixel
    output: integer between 1-5 represnting a class described above
    """
    pixel = tuple(pixel)
    rgb2label = {(255,0,0):0, (255,255,0):1, (0,255,0):2, 
                    (0,0,255):3, (0,255,255):4, (255,0,255):5}
    return rgb2label.get(pixel, 6)

In [ ]:
def crop_image(image, size):
    '''Crop sized centre of image  
    
    :param PIL image image: image to be cropped
    :return: cropped image
    :rtype: PIL image
    '''
    factor = (1-size)/2
    width, height = image.size
    box = factor*width,factor*height,(1-factor)*width,(1-factor)*height
    return image.crop(box)

In [75]:
cwd_eval = '/Users/jbaldauf/Documents/Tensorflow/OCT-project/Data/resulst_from_flow/'
cwd_data = '/Users/jbaldauf/Documents/Tensorflow/OCT-project/Data/Data_all/Multiple/'
image = 60
box_size = 48
data_gt_name = 'Image0%s.png'%str(image)
data_cnn_name = 'Image0%s_cnn_1_%s.png'%(str(image), str(box_size))
data_cnn_em_name = 'Image0%s_cnn_em_1_%s.png'%(str(image), str(box_size))

In [83]:
dataset = {}
dataset['im_gt'] = np.asarray(crop_image(Image.open(cwd_data + data_gt_name),0.6))
dataset['im_cnn'] = np.asarray(crop_image(Image.open(cwd_eval + data_cnn_name),0.6))
dataset['im_cnn_em'] = np.asarray(crop_image(Image.open(cwd_eval + data_cnn_em_name),0.6))

for data in dataset:
    dataset[data] = dataset[data].reshape(-1,3)
    dataset[data] = [getCenterLabel(dataset[data][i]) for i in xrange(len(dataset[data]))]


In [84]:
metrics.f1_score(dataset['im_gt'], dataset['im_cnn'], average= None)

/usr/local/lib/python2.7/site-packages/sklearn/metrics/classification.py:1074: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


array([ 0.8958454 ,  0.91450894,  0.89603748,  0.83882187,  0.58259474,
        0.561425  ,  0.        ])

In [85]:
metrics.f1_score(dataset['im_gt'], dataset['im_cnn_em'], average= None)

array([ 0.90449483,  0.92448675,  0.91370808,  0.86016425,  0.58557283,
        0.60124547,  0.        ])

In [81]:
metrics.f1_score(dataset['im_gt'], dataset['im_cnn'], average= None)

array([ 0.44632079,  0.91450894,  0.89603748,  0.83882187,  0.58259474,
        0.561425  ,  0.50022054])

In [82]:
metrics.f1_score(dataset['im_gt'], dataset['im_cnn_em'], average= None)

array([ 0.45218214,  0.92448675,  0.91370808,  0.86016425,  0.58557283,
        0.60124547,  0.50022054])

In [88]:
dataset

{}

In [51]:
def crop_image(image, size):
    '''Crop sized centre of image  
    
    :param PIL image image: image to be cropped
    :return: cropped image
    :rtype: PIL image
    '''
    factor = (1-size)/2
    width, height = image.size
    box = factor*width,factor*height,(1-factor)*width,(1-factor)*height
    return image.crop(box)

In [52]:
size=0.6
img_label = crop_image(img_label,size)

In [55]:
img_label = Image.open(cwd_eval + 'Image001.png')
old_size = img_label.size
img_label = img_label.transform((224,224), Image.EXTENT, (0,0,old_size[0],old_size[1]))

##Converting image size in cm to pixel for ppt

In [61]:
w_cm = 12.58
w_pix = 1500
sizes_pix =[24,30,36,42,48,54,60]
sizes_cm = [(w_cm/w_pix)*pix for pix in sizes_pix]
sizes_cm

[0.20128000000000001,
 0.25160000000000005,
 0.30192,
 0.35224,
 0.40256000000000003,
 0.45288000000000006,
 0.5032000000000001]

In [43]:
cwd_eval = '/Users/jbaldauf/Documents/admin/pollinateEnergy/'
img_label = Image.open(cwd_eval + 'julia.jpg')

In [45]:
crop_image(image, size)

NameError: name 'crop_image' is not defined

##understand pickeling limit and work around it

In [3]:
test_rand = np.random.random((1000,90,90,3))


In [4]:
test_rand = test_rand.__reduce__()

In [13]:
test_rand[1]

(numpy.ndarray, (0,), 'b')

In [8]:
def save_pickeldata(train_images, pickle_file):
    '''Save dataset of images and labels in pickle format

    :param np.float32 images: RGB images with shape (training_size, input_size, input_size, 3)
    :param np.float32 labels: labels with shape (training_size, num_labels)
    :param str pickle_file: path and filename to save to
    '''
    try:
        f = open(pickle_file, 'wb')
        save = {
            'images': test_rand,
            }
        pickle.dump(save, f, pickle.HIGHEST_PROTOCOL)
        f.close()
    except Exception as e:
        print('Unable to save data to', pickle_file, ':', e)
        raise
    statinfo = os.stat(pickle_file)
    print('Compressed pickle size:', statinfo.st_size)


In [9]:
cwd_eval = '/Users/jbaldauf/Documents/admin/pollinateEnergy/'
os.chdir(cwd_eval)
save_pickeldata(test_rand,'test.pickle')

('Compressed pickle size:', 194400173)


In [10]:
def load_data(pickle_file):
	'''Loads data prepared for this model from a pickle file
	
	:param str pickle_file: name of file to be loaded
	:param str cwd: path to file
	:return: images: images with shape (data_size, input_size, input_size, 3)
	:rtype: np.float32
	:return: labels: labels with shape (data_size, num_labels)
	:rtype: np.float32
	'''
	with open(pickle_file, 'rb') as f:
		save = pickle.load(f)
		images = save['images']
		del save  # hint to help gc free up memory
		print('All images and labels', images.shape, labels.shape)
	return images, labels

In [11]:
load_data('test.pickle')

AttributeError: 'tuple' object has no attribute 'shape'